### ISSUE TITLE
Missing documentation?

### ISSUE THREAD

**Issue by elmonten** [PatrickLeBlanc/LTNLDA#4]
Hello,

I was wondering if there were some missing documentation. I am not very familiar with all the maths behind your tool; however I fail to see in which part of the [Perplexity vignette ](http://127.0.0.1:25848/library/LTNLDA/doc/Perplexity.html) is specified how to optimize for `k` since it's always set to 1. Or are we supposed to run it multiple times with different k and check for the perplexity parameter?

Thanks a lot in advance for your help!

Cheers,
Elena

**Comment by PatrickLeBlanc** [comment]
Elena,

To change the number of topics/subcommunities `K`, you can change the parameter input to the `LTNLDA` function as described in the documentation [here](https://github.com/PatrickLeBlanc/LTNLDA/blob/master/R/Gibbs_Sampler.R) and rerun the model.  To change which topic/subcommunity you're analyzing for MCMC diagnostics, `k`, you can change the value of `k` where it is specified in the vignette.  Note that if you set `k` to be greater than `K` you'll encounter an error.  

Best,
Patrick

**Comment by elmonten** [comment]
Hello Patrick,

Thank you for your response. I have indeed noticed the `k` parameter can be changed, but I was wondering if you had also implemented a way to optimize the `k` for a given dataset. 

Best,
Elena

**Comment by PatrickLeBlanc** [comment]
The `k` parameter isn't really something that can be optimized - you're simply checking the topic/subcommunity that is associated with that value of `k`. 

Trying to optimize the number of topics/subcommunities `K`, is still something of an open problem for LDA type models.  The original [paper](https://dl.acm.org/doi/pdf/10.5555/944919.944937) recommended changing `K` and evaluating perplexity on some held-out test set (or cross-validation) and choosing the "elbow" in the perplexity curve.  This is what we did in our paper. 
 Other approaches exist (like Hierarchical Dirichlet Processes) but that's about as good as any other approach that has been tried.

**Comment by elmonten** [comment]
Thank you very much for the clarification and help, Patrick!
